import Foundation

/// Secret approval context shown to the local operator before a command runs.
public struct ApprovalRequest: Codable, Equatable, Sendable {
    private enum CodingKeys: String, CodingKey {
        case command
        case cwd
        case expiresAt
        case nonce
        case overrideEnv
        case overriddenAliases
        case reason
        case requestID
        case resolvedExecutable
        case reusableUses
        case secrets
    }

    /// Default reusable approval count when older daemon payloads omit it.
    public static let defaultReusableUses: Int = 3

    /// Stable request identifier generated by the daemon.
    public var requestID: String
    /// Daemon nonce that binds the request to one response.
    public var nonce: String
    /// Human-readable reason supplied by the requesting command.
    public var reason: String
    /// Command argv that will receive the approved secrets.
    public var command: [String]
    /// Working directory for the command.
    public var cwd: String
    /// Resolved executable path when the daemon can determine it.
    public var resolvedExecutable: String?
    /// Approval expiration timestamp.
    public var expiresAt: Date
    /// Secret references requested for this command.
    public var secrets: [RequestedSecret]
    /// Whether approved values will replace existing environment variables.
    public var overrideEnv: Bool
    /// Existing environment aliases that will be replaced.
    public var overriddenAliases: [String]
    /// Maximum command launches covered by a reusable approval.
    public var reusableUses: Int

    /// Creates an approval request payload.
    public init(
        requestID: String,
        nonce: String,
        reason: String,
        command: [String],
        cwd: String,
        expiresAt: Date,
        secrets: [RequestedSecret],
        resolvedExecutable: String? = nil,
        overrideEnv: Bool = false,
        overriddenAliases: [String] = [],
        reusableUses: Int = Self.defaultReusableUses
    ) {
        self.requestID = requestID
        self.nonce = nonce
        self.reason = reason
        self.command = command
        self.cwd = cwd
        self.resolvedExecutable = resolvedExecutable
        self.expiresAt = expiresAt
        self.secrets = secrets
        self.overrideEnv = overrideEnv
        self.overriddenAliases = overriddenAliases
        self.reusableUses = reusableUses
    }

    /// Decodes daemon payloads while preserving compatibility with older fields.
    public init(from decoder: Decoder) throws {
        let container: KeyedDecodingContainer<CodingKeys> = try decoder.container(keyedBy: CodingKeys.self)
        requestID = try container.decode(String.self, forKey: .requestID)
        nonce = try container.decode(String.self, forKey: .nonce)
        reason = try container.decode(String.self, forKey: .reason)
        command = try container.decode([String].self, forKey: .command)
        cwd = try container.decode(String.self, forKey: .cwd)
        resolvedExecutable = try container.decodeIfPresent(String.self, forKey: .resolvedExecutable)
        expiresAt = try container.decode(Date.self, forKey: .expiresAt)
        secrets = try container.decode([RequestedSecret].self, forKey: .secrets)
        overrideEnv = try container.decodeIfPresent(Bool.self, forKey: .overrideEnv) ?? false
        overriddenAliases = try container.decodeIfPresent([String].self, forKey: .overriddenAliases) ?? []
        reusableUses = try container.decodeIfPresent(Int.self, forKey: .reusableUses) ?? Self.defaultReusableUses
    }
}
