#!/usr/bin/env bash

# shellcheck disable=SC2034
AGENT_SECRET_APP_NAME="Agent Secret"
AGENT_SECRET_APP_DISPLAY_NAME="Agent Secret"
AGENT_SECRET_APP_EXECUTABLE="Agent Secret"
AGENT_SECRET_APP_BUNDLE_ID="com.kovyrin.agent-secret"
AGENT_SECRET_DAEMON_BUNDLE_ID="com.kovyrin.agent-secret.daemon"
AGENT_SECRET_APP_CATEGORY="public.app-category.developer-tools"
AGENT_SECRET_ICON_FILE="AppIcon"
AGENT_SECRET_MIN_MACOS_VERSION="14.0"
AGENT_SECRET_INFO_DICTIONARY_VERSION="6.0"
AGENT_SECRET_DEFAULT_VERSION="0.1.0"
AGENT_SECRET_DEFAULT_BUNDLE_VERSION="1"
